version: '3'
services:
  logs:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=logs
      - TZ=Asia/Kolkata  
  http1:
    image: "winnovature/unitia:production" 
    ports:
      - "8001:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "router1"
      - "router2"
    environment:
      - module=http
      - TZ=Asia/Kolkata  
  http2:
    image: "winnovature/unitia:production"
    ports:
      - "8002:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "router1"
      - "router2"
    environment:
      - module=http
      - TZ=Asia/Kolkata
  smpp:
    image: "winnovature/unitia:production"
    ports:
      - "2775:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "router1"
      - "router2"
    environment:
      - module=smpp
      - TZ=Asia/Kolkata
  dnreceiver1:
    image: "winnovature/unitia:production"
    ports:
      - "6001:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "submission"
    environment:
      - module=dnreceiver
      - TZ=Asia/Kolkata
  dnreceiver2:
    image: "winnovature/unitia:production"
    ports:
      - "6002:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "submission"
    environment:
      - module=dnreceiver
      - TZ=Asia/Kolkata
  submission:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    environment:
      - module=submission
      - TZ=Asia/Kolkata
  delivery:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "scheduledb"
    environment:
      - module=delivery
      - TZ=Asia/Kolkata
  dnsql:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "unitiadb"
      - "kannel1"
      - "pinnaclkanneldb"
      - "tagkanneldb"
      - "tagtele"
      - "pinnacle"
    environment:
      - module=dnsql
      - TZ=Asia/Kolkata
  scheduledb:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "dnpostdb" 
    environment:
      - module=scheduledb
      - TZ=Asia/Kolkata
  dnpostdb:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "dbtoredis"
    environment:
      - module=dnpostdb
      - TZ=Asia/Kolkata
  dbtoredis:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "tablereader"
    environment:
      - module=dbtoredis
      - TZ=Asia/Kolkata
  tablereader:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "dnhttppost"
    environment:
      - module=tablereader
      - TZ=Asia/Kolkata
  dnhttppost:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "redisqueue1"
    environment:
      - module=dnhttppost
      - TZ=Asia/Kolkata
  router1:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "redisqueue1"
      - "kannel1"
      - "tagtele"
      - "pinnacle"
    environment:
      - module=router
      - redis=redisqueue1 
      - TZ=Asia/Kolkata
  router2:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "redisqueue2"
      - "kannel1"
      - "tagtele"
      - "pinnacle"
    environment:
      - module=router
      - redis=redisqueue2
      - TZ=Asia/Kolkata
  redisqueue1:
    image: "redis:6.0-alpine3.12"
    ports:
      - "2001:6379" 
    volumes:
      - /home/unitia/production/redisqueue1/data/:/data
  redisqueue2:
    image: "redis:6.0-alpine3.12"
    ports:
      - "2002:6379"
    volumes:
      - /home/unitia/production/redisqueue2/data/:/data
  kannel1:
    image: "winnovature/kannel:sqldn"
    ports:
      - "13013:13013" # smsbox
      - "13000:13000" # kannel admin
    depends_on:
      - kannelconfig
      - dn
    volumes:
      - "/home/unitia/production/spool/kannel1:/var/spool/kannel"
      - "/logs/kannel1:/var/log/kannel"
      - "/etc/hosts:/etc/hosts"
      - "/home/unitia/production/kannel1:/etc/kannel"
      - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    environment:
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
  pinnacle:
    image: "winnovature/kannel:sqldn"
    ports:
      - "13113:13013" # smsbox
      - "13100:13000" # kannel admin
    depends_on:
      - kannelconfig
      - dn
    volumes:
      - "/home/unitia/production/spool/pinnacle:/var/spool/kannel"
      - "/logs/pinnacle:/var/log/kannel"
      - "/etc/hosts:/etc/hosts"
      - "/home/unitia/production/pinnacle:/etc/kannel"
      - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    environment:
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
  tagtele:
    image: "winnovature/kannel:sqldn"
    ports:
      - "13213:13013" # smsbox
      - "13200:13000" # kannel admin
    depends_on:
      - kannelconfig
      - dn
    volumes:
      - "/home/unitia/production/spool/tagtele:/var/spool/kannel"
      - "/logs/tagtele:/var/log/kannel"
      - "/etc/hosts:/etc/hosts"
      - "/home/unitia/production/tagtele:/etc/kannel"
      - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    environment:
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
  unitiadb:
    image: "winnovature/mariadb:production"
    ports:
      -  "7005:3306"
    volumes:
      - "/home/unitia/production/mysql:/var/lib/mysql"
      - "/home/unitia/production/mysql/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel 
      - TZ=Asia/Kolkata
  pinnaclkanneldb:
    image: "winnovature/mariadb:production"
    ports:
      -  "7006:3306"
    volumes:
      - "/home/unitia/production/pinnaclkanneldb:/var/lib/mysql"
      - "/home/unitia/production/pinnaclkanneldb/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel
      - TZ=Asia/Kolkata
  tagkanneldb:
    image: "winnovature/mariadb:production"
    ports:
      -  "7007:3306"
    volumes:
      - "/home/unitia/production/tagkanneldb:/var/lib/mysql"
      - "/home/unitia/production/tagkanneldb/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel
      - TZ=Asia/Kolkata
  kannelconfig:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    depends_on:
      - "unitiadb"
    environment:
      - module=kannelconfig
      - TZ=Asia/Kolkata
  dn:
    image: "dn-haproxy:latest"
    ports:
      - "8777:8080"
    depends_on:
      - "dnreceiver1"
      - "dnreceiver2"
  http:
    image: "http-haproxy:latest"
    ports:
      - "9090:8080"
    depends_on:
      - "http1"
      - "http2"
